# Generated by Django 5.2.8 on 2025-12-11 04:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('sales', '0002_order_balance_due_order_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial Payment'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pricing.item'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField()),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('this_bill_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial Payment'), ('unpaid', 'Unpaid')], default='paid', max_length=20)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('store_name', models.TextField(default='Bilal Poultry Traders')),
                ('store_address', models.TextField(blank=True, null=True)),
                ('store_phone', models.TextField(default='0331-3939373')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reprint_count', models.IntegerField(default=0)),
                ('last_reprinted_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='sales.client')),
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='sales.order')),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('receipt', models.ForeignKey(db_column='receipt_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.receipt')),
            ],
            options={
                'db_table': 'receipt_items',
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='receipts_receipt_0f1a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_date'], name='receipts_receipt_eac4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['customer', 'receipt_date'], name='receipts_client__cce2db_idx'),
        ),
    ]
