# Generated by Django 5.2.8 on 2025-12-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_order_payment_method_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='order',
            field=models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='sales.order'),
        ),
    ]
